## Numpy

numerical python
It is a python library to work on arrays , matrice , large-scientific calculation
### Numpy
__________________________
* provides extension package in python to work on multi dimentional array
* It is very efficient compared to list

# 1-D array

In [16]:
import numpy as np
l = np.array([1,2.90001,"string",2,1,4])
print(l)
ll = np.arange(10)
print(ll)
lll = np.arange(10,50)
print(lll , type(lll))
i = np.arange(10,50,2)
print(i,"\n",i.ndim)

['1' '2.90001' 'string' '2' '1' '4']
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] <class 'numpy.ndarray'>
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48] 
 1


## 2-D array

In [20]:
l = np.array([[1,2,3],[4,5,6]])
print(l.shape,"\n",l.ndim)

(2, 3) 
 2


## 3-D array

In [34]:
l = np.array([ [ [1,2],[5,6] ],[ [8,9],[11,12] ],[ [2,3],[5,6] ] ])
print("\n",l.ndim,"\n",l.shape)
l


 3 
 (3, 2, 2)


array([[[ 1,  2],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]],

       [[ 2,  3],
        [ 5,  6]]])

## linspace
linear space
Used to divide the data into equal space

In [68]:
l = np.linspace(1,10,4)
print(l)

[ 1.  4.  7. 10.]


### Random

* np.random.randint(5)
* np.random.rand(10)
* np.random.randn(19)

In [65]:
print("randint()")
print(np.random.randint(5,10))
print("randn")
print(np.random.randn(5))
print("rand")
print(np.random.rand(3,4))

randint()
8
randn
[-0.06857263 -1.12375653 -0.04974367 -0.31303748  0.98018107]
rand
[[0.96888068 0.40009732 0.9241603  0.61474957]
 [0.59972874 0.24171075 0.98767394 0.38698235]
 [0.30494441 0.94512803 0.82577603 0.95865017]]


### eye

Identity matrix
[1 0 0]
[0 1 0]
[0 0 1]

In [69]:
a = np.eye(4)
b = np.eye(4,5)
print(a,"\n\n",b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


### Zeroes and Ones

In [78]:
a = np.zeros((2,3,8))
b = np.ones((2,3,7))
print("Zeros\n",a , "\nOnes" , b)

Zeros
 [[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]] 
Ones [[[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]]


### diagonal 
diag

In [82]:
print(np.diag(np.diag([3,5,6])))
print(np.diag([1,2,3,4,5]))

[3 5 6]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


## Calculation using numpy arrays

In [114]:
a = np.array([4,2,133,1121,523,64,124,6456])
print("Mean = ",np.mean(a))
print("Median = ",np.median(a))
print("sum = ",np.sum(a))
print("sum = ",sum(a))
print("min = ",min(a))
print("max = ",max(a))
print("Standard deviation = ",np.std(a))
b = np.array([[4,3],[1,2]])
print("mean = ",np.mean(b))
print("median = ",np.median(b))
print("sum = ",np.sum(b))
print("sum = ",sum(b))
#print(min(b))
#print(max(b))
print("Standard deviation = ",np.std(b))
print(b)
print("Sum with Axis column ",np.sum(b,axis = 0))
print("Sum with Axis Row ",np.sum(b,axis = 1))
print("mean with Axis column ",np.mean(b,axis = 0))
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[1,2,3]])
x+y

Mean =  1053.375
Median =  128.5
sum =  8427
sum =  8427
min =  2
max =  6456
Standard deviation =  2072.7546850447593
mean =  2.5
median =  2.5
sum =  10
sum =  [5 5]
Standard deviation =  1.118033988749895
[[4 3]
 [1 2]]
Sum with Axis column  [5 5]
Sum with Axis Row  [7 3]
mean with Axis column  [2.5 2.5]


array([[2, 4, 6],
       [5, 7, 9]])